name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:

  complete:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1

  test:
    strategy:
      matrix:
        formula:
        - "stellar-xdr"
        - "stellar-core-futurenet"
        - "soroban-cli"
    runs-on: ${{ matrix.sys.os }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: time brew install --formula --build-from-source ./Formula/${{ matrix.formula }}.rb
