name: Test

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:

  complete:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        formula:
        - stellar-xdr
        - stellar-core-futurenet
        - soroban-cli
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: Homebrew/actions/setup-homebrew@24adfe27fc8e515deb1753996e07c111c1c16a96
    - name: Install Dependencies
      run: brew install --verbose --only-dependencies --formula ./Formula/${{ matrix.formula }}.rb
    - name: Install Formula
      run: brew install --verbose --build-from-source --formula ./Formula/${{ matrix.formula }}.rb
    - name: Test Formula
      run: brew test --verbose --force ${{ matrix.formula }}
