name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:

  complete:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        formula:
        - stellar-xdr
        - stellar-core-futurenet
        - soroban-cli
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: Homebrew/actions/setup-homebrew@24adfe27fc8e515deb1753996e07c111c1c16a96
    - run: brew install --formula --build-from-source ./Formula/${{ matrix.formula }}.rb
    - run: brew test --force --verbose ${{ matrix.formula }}
